# Generated by Django 4.2.7 on 2025-09-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes about this payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Full', 'Full Payment'), ('Partial', 'Partial Payment'), ('Advance', 'Advance Payment')], default='Full', max_length=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount still owed by tenant', max_digits=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='due_date',
            field=models.IntegerField(default=1, help_text='Day of the month when rent is due (1-31)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='rent_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Partial', 'Partial'), ('Overdue', 'Overdue')], default='Unpaid', max_length=10),
        ),
    ]
