# Generated by Django 4.2.7 on 2025-09-13 20:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0002_payment_notes_payment_payment_type_tenant_amount_due_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('response_data', models.JSONField(blank=True, help_text='API response data', null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='rental_app.tenant')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
