# Generated by Django 4.2.7 on 2025-09-15 15:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0003_smslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_id', models.UUIDField(help_text='Original payment ID before deletion')),
                ('tenant_name', models.CharField(help_text='Tenant name at time of deletion', max_length=100)),
                ('tenant_apartment', models.CharField(help_text='Apartment number at time of deletion', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Paid', max_length=20)),
                ('payment_type', models.CharField(choices=[('Full', 'Full Payment'), ('Partial', 'Partial Payment'), ('Advance', 'Advance Payment')], default='Full', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('archived_by', models.CharField(default='System', max_length=100)),
                ('archive_reason', models.CharField(default='Payment deleted', max_length=200)),
            ],
            options={
                'verbose_name': 'Archived Payment',
                'verbose_name_plural': 'Archived Payments',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchivedTenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_id', models.UUIDField(help_text='Original tenant ID before deletion')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('apartment_number', models.CharField(max_length=20)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Partial', 'Partial'), ('Overdue', 'Overdue')], default='Unpaid', max_length=20)),
                ('due_date', models.IntegerField(default=1, help_text='Day of month when rent is due')),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('archived_by', models.CharField(default='System', max_length=100)),
                ('archive_reason', models.CharField(default='Tenant deleted', max_length=200)),
            ],
            options={
                'verbose_name': 'Archived Tenant',
                'verbose_name_plural': 'Archived Tenants',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_name', models.CharField(max_length=100)),
                ('apartment_number', models.CharField(max_length=20)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('status_changed', 'Status Changed'), ('amount_changed', 'Amount Changed')], max_length=20)),
                ('description', models.TextField()),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_by', models.CharField(default='System', max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_name', models.CharField(max_length=100)),
                ('apartment_number', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('rent_paid', 'Rent Paid'), ('rent_unpaid', 'Rent Unpaid'), ('status_changed', 'Status Changed'), ('amount_changed', 'Amount Changed'), ('due_date_changed', 'Due Date Changed')], max_length=20)),
                ('description', models.TextField()),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_by', models.CharField(default='System', max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tenant History',
                'verbose_name_plural': 'Tenant Histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
